import {
  IsEmail,
  IsEnum,
  IsNotEmpty,
  IsOptional,
  IsString,
  Matches,
  MaxLength,
  MinLength,
} from 'class-validator';
import { Role } from 'src/public/user/user.type';

export class RegisterDto {
  @IsString()
  @IsNotEmpty()
  name!: string;

  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @IsString()
  @MinLength(8)
  @MaxLength(32)
  @Matches(
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&#^()_\-+=])[A-Za-z\d@$!%*?&#^()_\-+=]+$/,
    {
      message:
        'Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character.',
    },
  )
  password!: string;

  @IsOptional()
  phone?: string;

  @IsEnum(Role)
  role!: Role;
}

// {
//   "name": "Sakib Kahadi",
//   "email": "sakib@example.com",
//   "password": "StrongPassword123",
//   "phone": "01712345678",
// role": "EMPLOYEE",

//   "employeeId": "EMP-0001"(generated by system),
// }
